run_name: exp1
seed: 42
device: auto  # "cpu", "cuda", or "mps"; "auto" picks best
data:
  path: data/input.txt
  block_size: 256        # sequence length
  train_frac: 0.9
  num_workers: 0
  batch_size: 16
model:
  vocab_size: 256        # byte-level
  d_model: 256
  n_heads: 4
  d_ff: 1024
  n_layers: 4
  dropout: 0.1
  use_bias: true
optim:
  lr: 0.0003
  weight_decay: 0.01
  betas: [0.9, 0.95]
train:
  max_steps: 1000
  log_every: 50
  eval_every: 200
  ckpt_dir: runs
  grad_clip: 1.0
  amp: true
sched:
  warmup_steps: 100
  min_lr: 0.00005
